# Generated by Django 6.0.1 on 2026-02-14 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketra', '0005_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhistory',
            name='interaction_type',
            field=models.CharField(default='view', max_length=20),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketra.product'),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
