# Generated by Django 6.0.1 on 2026-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketra', '0007_section_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='section',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers first)'),
        ),
    ]
